[package]
name = "yams-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rustix.workspace = true
sha2.workspace = true
thiserror.workspace = true
unicode-general-category.workspace = true

[dev-dependencies]
tempfile.workspace = true
